apiVersion: v1
kind: Secret
metadata: 
  name: risingwave-aliyun-oss-credentials
stringData:
  AccountName: your-oss-account-name
  AccountKey: your-oss-account-key
---
apiVersion: risingwave.risingwavelabs.com/v1alpha1
kind: RisingWave
metadata:
  name: risingwave-in-memory-aliyun-oss
spec:
  metaStore:
    memory: true
  stateStore:
    aliyunOss:
      credentials:
        secretName: risingwave-aliyun-oss-credentials
      bucket: your-aliyun-oss-bucket
      root: risingwave
      endpoint: https://<your-region>.aliyuncs.com
  image: ghcr.io/risingwavelabs/risingwave:v0.19.1
  components:
    meta:
      nodeGroups:
      - replicas: 1
        name: ""
    frontend:
      nodeGroups:
      - replicas: 1
        name: ""
    compute:
      nodeGroups:
      - replicas: 1
        name: ""
    compactor:
      nodeGroups:
      - replicas: 1
        name: ""