{
 "title": "RisingWave Dashboard",
 "description": "RisingWave Dashboard",
 "tags": [ "risingwave" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(up{risingwave_name=~\".+\"}, namespace)"
    }
   },
   {
    "name": "instance",
    "label": "RisingWave",
    "query": {
     "query": "label_values(up{namespace=\"$namespace\", risingwave_name=~\".+\"}, risingwave_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(worker_num{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}) by (worker_type)",
     "legendFormat": "{{worker_type}}"
    }
   ]
  },
  {
   "title": "Node Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}) by (risingwave_component,pod)",
     "legendFormat": "{{risingwave_component}} @ {{pod}}"
    }
   ]
  },
  {
   "title": "Node CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (risingwave_component,pod)",
     "legendFormat": "{{risingwave_component}} @ {{pod}}"
    }
   ]
  },
  {
   "title": "Meta Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(meta_num{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}) by (worker_addr,role)",
     "legendFormat": "{{worker_addr}} @ {{role}}"
    }
   ]
  },
  { "title": "Streaming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Source Throughput(rows)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "rows/s" } },
   "targets": [
    {
     "expr": "rate(stream_source_output_rows_counts{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "source={{source_name}} {{source_id}} @ {{pod}}"
    }
   ]
  },
  {
   "title": "Source Throughput(rows) Per Partition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "rows/s" } },
   "targets": [
    {
     "expr": "rate(partition_input_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "actor={{actor_id}} source={{source_id}} partition={{partition}}"
    }
   ]
  },
  {
   "title": "Source Throughput(bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "MB/s" } },
   "targets": [
    {
     "expr": "(sum by (source_id)(rate(partition_input_bytes{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])))/(1000*1000)",
     "legendFormat": "source={{source_id}}"
    }
   ]
  },
  {
   "title": "Source Throughput(bytes) Per Partition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "MB/s" } },
   "targets": [
    {
     "expr": "(rate(partition_input_bytes{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))/(1000*1000)",
     "legendFormat": "actor={{actor_id}} source={{source_id}} partition={{partition}}"
    }
   ]
  },
  {
   "title": "Source Throughput(rows) per barrier",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "rows/s" } },
   "targets": [
    {
     "expr": "rate(stream_source_rows_per_barrier_counts{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "actor={{actor_id}} source={{source_id}} @ {{pod}}"
    }
   ]
  },
  {
   "title": "Barrier Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "all_barrier_nums{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}",
     "legendFormat": "all_barrier"
    },
    {
     "expr": "in_flight_barrier_nums{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}",
     "legendFormat": "in_flight_barrier"
    }
   ]
  },
  {
   "title": "Barrier Send Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(meta_barrier_send_duration_seconds_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "barrier_send_latency_p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(meta_barrier_send_duration_seconds_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "barrier_send_latency_p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(meta_barrier_send_duration_seconds_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "barrier_send_latency_p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(meta_barrier_send_duration_seconds_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "barrier_send_latency_p999"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(meta_barrier_send_duration_seconds_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "barrier_send_latency_pmax"
    },
    {
     "expr": "rate(meta_barrier_send_duration_seconds_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) / rate(meta_barrier_send_duration_seconds_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "barrier_send_latency_avg"
    }
   ]
  },
  {
   "title": "Barrier Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(meta_barrier_duration_seconds_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "barrier_latency_p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(meta_barrier_duration_seconds_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "barrier_latency_p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(meta_barrier_duration_seconds_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "barrier_latency_p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(meta_barrier_duration_seconds_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "barrier_latency_p999"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(meta_barrier_duration_seconds_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "barrier_latency_pmax"
    },
    {
     "expr": "rate(meta_barrier_duration_seconds_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) / rate(meta_barrier_duration_seconds_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "barrier_latency_avg"
    }
   ]
  },
  {
   "title": "Barrier In-Flight Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(stream_barrier_inflight_duration_seconds_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "barrier_inflight_latency_p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(stream_barrier_inflight_duration_seconds_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "barrier_inflight_latency_p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(stream_barrier_inflight_duration_seconds_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "barrier_inflight_latency_p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(stream_barrier_inflight_duration_seconds_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "barrier_inflight_latency_p999"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(stream_barrier_inflight_duration_seconds_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "barrier_inflight_latency_pmax"
    },
    {
     "expr": "max(sum by(le, pod)(rate(stream_barrier_inflight_duration_seconds_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))  / sum by(le, pod)(rate(stream_barrier_inflight_duration_seconds_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "barrier_inflight_latency_avg"
    }
   ]
  },
  {
   "title": "Barrier Sync Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(stream_barrier_sync_storage_duration_seconds_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le,pod))",
     "legendFormat": "barrier_sync_latency_p50 - {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(stream_barrier_sync_storage_duration_seconds_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le,pod))",
     "legendFormat": "barrier_sync_latency_p90 - {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(stream_barrier_sync_storage_duration_seconds_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le,pod))",
     "legendFormat": "barrier_sync_latency_p99 - {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(stream_barrier_sync_storage_duration_seconds_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le,pod))",
     "legendFormat": "barrier_sync_latency_p999 - {{pod}}"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(stream_barrier_sync_storage_duration_seconds_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le,pod))",
     "legendFormat": "barrier_sync_latency_pmax - {{pod}}"
    },
    {
     "expr": "sum by(le, pod)(rate(stream_barrier_sync_storage_duration_seconds_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))  / sum by(le, pod)(rate(stream_barrier_sync_storage_duration_seconds_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "barrier_sync_latency_avg - {{pod}}"
    }
   ]
  },
  {
   "title": "Barrier Wait Commit Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(meta_barrier_wait_commit_duration_seconds_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "barrier_wait_commit_latency_p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(meta_barrier_wait_commit_duration_seconds_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "barrier_wait_commit_latency_p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(meta_barrier_wait_commit_duration_seconds_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "barrier_wait_commit_latency_p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(meta_barrier_wait_commit_duration_seconds_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "barrier_wait_commit_latency_p999"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(meta_barrier_wait_commit_duration_seconds_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "barrier_wait_commit_latency_pmax"
    },
    {
     "expr": "rate(meta_barrier_wait_commit_duration_seconds_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) / rate(meta_barrier_wait_commit_duration_seconds_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "barrier_wait_commit_avg"
    }
   ]
  },
  {
   "title": "Streaming Actors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executor Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "rows/s" } },
     "targets": [
      {
       "expr": "rate(stream_executor_row_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}->{{executor_id}}"
      }
     ]
    },
    {
     "title": "Actor Backpressure",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(stream_actor_output_buffer_blocking_duration_ns{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) / 1000000000",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Actor Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(actor_memory_usage[$__rate_interval])",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Actor Input Blocking Time Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(stream_actor_input_buffer_blocking_duration_ns{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) / 1000000000",
       "legendFormat": "{{actor_id}}->{{upstream_fragment_id}}"
      }
     ]
    },
    {
     "title": "Actor Barrier Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_barrier_time{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Actor Processing Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_processing_time{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Actor Execution Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_actor_execution_time{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Actor Input Row",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "row" } },
     "targets": [
      {
       "expr": "rate(stream_actor_in_record_cnt{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Actor Output Row",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "row" } },
     "targets": [
      {
       "expr": "rate(stream_actor_out_record_cnt{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Fast Poll Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_fast_poll_duration{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Fast Poll Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(stream_actor_fast_poll_cnt{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Fast Poll Avg Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_fast_poll_duration{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) / rate(stream_actor_fast_poll_cnt{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Slow Poll Total Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_slow_poll_duration{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Slow Poll Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(stream_actor_slow_poll_cnt{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Slow Poll Avg Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_slow_poll_duration{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) / rate(stream_actor_slow_poll_cnt{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Poll Total Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_poll_duration{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Poll Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(stream_actor_poll_cnt{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Poll Avg Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_poll_duration{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) / rate(stream_actor_poll_cnt{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Idle Total Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_idle_duration{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Idle Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(stream_actor_idle_cnt{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Idle Avg Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_idle_duration{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) / rate(stream_actor_idle_cnt{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Scheduled Total Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_scheduled_duration{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Scheduled Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(stream_actor_scheduled_cnt{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Scheduled Avg Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_scheduled_duration{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) / rate(stream_actor_scheduled_cnt{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Join Executor Cache",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(stream_join_lookup_miss_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "cache miss {{actor_id}} {{side}}"
      },
      {
       "expr": "rate(stream_join_lookup_total_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "total lookups {{actor_id}} {{side}}"
      },
      {
       "expr": "rate(stream_join_insert_cache_miss_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "cache miss when insert {{actor_id}} {{side}}"
      },
      {
       "expr": "rate(stream_join_may_exist_true_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "may_exist true when insert {{actor_id}} {{side}}"
      }
     ]
    },
    {
     "title": "Join Executor Barrier Align",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(rate(stream_join_barrier_align_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, actor_id, wait_side, risingwave_component, pod))",
       "legendFormat": "p90 {{actor_id}}.{{wait_side}} - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(stream_join_barrier_align_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, actor_id, wait_side, risingwave_component, pod))",
       "legendFormat": "p99 {{actor_id}}.{{wait_side}} - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(stream_join_barrier_align_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, actor_id, wait_side, risingwave_component, pod))",
       "legendFormat": "p999 {{actor_id}}.{{wait_side}} - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(1.0, sum(rate(stream_join_barrier_align_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, actor_id, wait_side, risingwave_component, pod))",
       "legendFormat": "pmax {{actor_id}}.{{wait_side}} - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "sum by(le, actor_id, wait_side, risingwave_component, pod)(rate(stream_join_barrier_align_duration_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum by(le,actor_id,wait_side,risingwave_component,pod) (rate(stream_join_barrier_align_duration_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "avg {{actor_id}}.{{wait_side}} - {{risingwave_component}} @ {{pod}}"
      }
     ]
    },
    {
     "title": "Join Actor Input Blocking Time Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(stream_join_actor_input_waiting_duration_ns{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) / 1000000000",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Join Actor Match Duration Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(stream_join_match_duration_ns{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]) / 1000000000",
       "legendFormat": "{{actor_id}}.{{side}}"
      }
     ]
    },
    {
     "title": "Join Cached Entries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
     "targets": [
      {
       "expr": "stream_join_cached_entries{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}",
       "legendFormat": "{{actor_id}} {{side}}"
      }
     ]
    },
    {
     "title": "Join Cached Rows",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
     "targets": [
      {
       "expr": "stream_join_cached_rows{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}",
       "legendFormat": "{{actor_id}} {{side}}"
      }
     ]
    },
    {
     "title": "Join Cached Estimated Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "stream_join_cached_estimated_size{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}",
       "legendFormat": "{{actor_id}} {{side}}"
      }
     ]
    },
    {
     "title": "Join Cached Seq Gap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(stream_join_cached_seq_gap_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, actor_id, side, operation, risingwave_component, pod))",
       "legendFormat": "p50 {{actor_id}}.{{side}}.{{operation}} - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(stream_join_cached_seq_gap_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, actor_id, side, operation, risingwave_component, pod))",
       "legendFormat": "p90 {{actor_id}}.{{side}}.{{operation}} - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(stream_join_cached_seq_gap_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, actor_id, side, operation, risingwave_component, pod))",
       "legendFormat": "p99 {{actor_id}}.{{side}}.{{operation}} - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(stream_join_cached_seq_gap_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, actor_id, side, operation, risingwave_component, pod))",
       "legendFormat": "p999 {{actor_id}}.{{side}}.{{operation}} - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(1.0, sum(rate(stream_join_cached_seq_gap_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, actor_id, side, operation, risingwave_component, pod))",
       "legendFormat": "pmax {{actor_id}}.{{side}}.{{operation}} - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "sum by(le, actor_id, side, operation, risingwave_component, pod)(rate(stream_join_cached_seq_gap_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum by(le,actor_id,side,operation,risingwave_component,pod) (rate(stream_join_cached_seq_gap_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "avg {{actor_id}}.{{side}}.{{operation}} - {{risingwave_component}} @ {{pod}}"
      }
     ]
    },
    {
     "title": "Aggregation Executor Cache Statistics For Each Key/State",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(stream_agg_lookup_miss_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "cache miss {{actor_id}}"
      },
      {
       "expr": "rate(stream_agg_lookup_total_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "total lookups {{actor_id}}"
      }
     ]
    },
    {
     "title": "Aggregation Executor Cache Statistics For Each StreamChunk",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(stream_agg_chunk_lookup_miss_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "chunk-level cache miss {{actor_id}}"
      },
      {
       "expr": "rate(stream_agg_chunk_lookup_total_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "chunk-level total lookups {{actor_id}}"
      }
     ]
    },
    {
     "title": "Aggregation Cached Keys",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
     "targets": [
      {
       "expr": "stream_agg_cached_keys{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}",
       "legendFormat": "{{actor_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Streaming Exchange",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fragment-level Remote Exchange Send Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(stream_exchange_frag_send_size{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{up_fragment_id}}->{{down_fragment_id}}"
      }
     ]
    },
    {
     "title": "Fragment-level Remote Exchange Recv Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(stream_exchange_frag_recv_size{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{up_fragment_id}}->{{down_fragment_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "User Streaming Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compute Errors by Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "sum(user_compute_error_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}) by (error_type, error_msg, fragment_id, executor_name)",
       "legendFormat": "{{error_type}}: {{error_msg}} ({{executor_name}}: fragment_id={{fragment_id}})"
      }
     ]
    },
    {
     "title": "Source Errors by Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "targets": [
      {
       "expr": "sum(user_source_error_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}) by (error_type, error_msg, fragment_id, table_id, executor_name)",
       "legendFormat": "{{error_type}}: {{error_msg}} ({{executor_name}}: table_id={{table_id}}, fragment_id={{fragment_id}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Batch Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exchange Recv Row Number",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "row" } },
     "targets": [
      {
       "expr": "batch_task_exchange_recv_row_number{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}",
       "legendFormat": "{{query_id}} : {{source_stage_id}}.{{source_task_id}} -> {{target_stage_id}}.{{target_task_id}}"
      }
     ]
    },
    {
     "title": "Batch Mpp Task Number",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "row" } },
     "targets": [
      {
       "expr": "batch_task_num{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  { "title": "Hummock", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Build and Sync Sstable Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(state_store_sync_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
     "legendFormat": "p50 - {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_sync_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
     "legendFormat": "p90 - {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_sync_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
     "legendFormat": "p99 - {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(state_store_sync_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
     "legendFormat": "pmax - {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "sum by(le, risingwave_component, pod) (rate(state_store_sync_duration_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum by(le, risingwave_component, pod) (rate(state_store_sync_duration_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "avg - {{risingwave_component}} @ {{pod}}"
    }
   ]
  },
  {
   "title": "Cache Ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_sst_store_block_request_counts{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (risingwave_component, pod, table_id, type)",
     "legendFormat": "{{table_id}} @ {{type}} - {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "sum(rate(file_cache_latency_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (op, pod)",
     "legendFormat": "file cache {{op}} @ {{pod}}"
    },
    {
     "expr": "sum(rate(file_cache_miss{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (pod)",
     "legendFormat": "file cache miss @ {{pod}}"
    }
   ]
  },
  {
   "title": "Read Ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_get_duration_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (risingwave_component,instanc,table_id)",
     "legendFormat": "get - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "sum(rate(state_store_range_reverse_scan_duration_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (risingwave_component,pod)",
     "legendFormat": "backward scan - {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "sum(rate(state_store_get_shared_buffer_hit_counts{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (risingwave_component,pod,table_id)",
     "legendFormat": "shared_buffer hit - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "sum(rate(state_store_iter_in_process_counts{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by(risingwave_component,pod,table_id)",
     "legendFormat": "iter - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    }
   ]
  },
  {
   "title": "Read Duration - Get",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(state_store_get_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "p50 - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_get_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "p90 - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_get_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "p99 - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(state_store_get_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "pmax - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "sum by(le, risingwave_component, pod, table_id)(rate(state_store_get_duration_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum by(le, risingwave_component, pod, table_id) (rate(state_store_get_duration_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "avg - {{table_id}} {{risingwave_component}} @ {{pod}}"
    }
   ]
  },
  {
   "title": "Read Duration - Iter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_iter_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "create_iter_time p90 - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_iter_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "create_iter_time p99 - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(state_store_iter_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "create_iter_time p999 - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(state_store_iter_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "create_iter_time pmax - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "sum by(le, risingwave_component, pod)(rate(state_store_iter_duration_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum by(le, risingwave_component,pod) (rate(state_store_iter_duration_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "create_iter_time avg - {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_iter_scan_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "pure_scan_time p90 - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_iter_scan_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "pure_scan_time p99 - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(state_store_iter_scan_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "pure_scan_time p999 - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(state_store_iter_scan_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "pure_scan_time pmax - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "sum by(le, risingwave_component, pod)(rate(state_store_scan_iter_duration_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum by(le, risingwave_component,pod) (rate(state_store_iter_scan_duration_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "pure_scan_time avg - {{risingwave_component}} @ {{pod}}"
    }
   ]
  },
  {
   "title": "Read Item Size - Get",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_get_key_size_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id)) + histogram_quantile(0.9, sum(rate(state_store_get_value_size_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "p90 - {{table_id}} {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_get_key_size_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id)) + histogram_quantile(0.99, sum(rate(state_store_get_value_size_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "p99 - {{table_id}} {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(state_store_get_key_size_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id)) + histogram_quantile(0.999, sum(rate(state_store_get_value_size_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "p999 - {{table_id}} {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(state_store_get_key_size_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id)) + histogram_quantile(1.0, sum(rate(state_store_get_value_size_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "pmax - {{table_id}} {{risingwave_component}} @ {{pod}}"
    }
   ]
  },
  {
   "title": "Read Item Size - Iter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_iter_size_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "p90 - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_iter_size_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "p99 - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(state_store_iter_size_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "p999 - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(state_store_iter_size_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "pmax - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    }
   ]
  },
  {
   "title": "Read Item Count - Iter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_iter_item_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "p90 - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_iter_item_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "p99 - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(state_store_iter_item_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "p999 - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(state_store_iter_item_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "pmax - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    }
   ]
  },
  {
   "title": "Read Throughput - Get",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_get_key_size_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by(risingwave_component, pod) + sum(rate(state_store_get_value_size_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by(risingwave_component, pod)",
     "legendFormat": "{{risingwave_component}} @ {{pod}}"
    }
   ]
  },
  {
   "title": "Read Throughput - Iter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_iter_size_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by(risingwave_component, pod)",
     "legendFormat": "{{risingwave_component}} @ {{pod}}"
    }
   ]
  },
  {
   "title": "Read Duration - MayExist",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(state_store_may_exist_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "p50 - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_may_exist_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "p90 - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_may_exist_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "p99 - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(state_store_may_exist_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "pmax - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "sum by(le, risingwave_component, pod, table_id)(rate(state_store_may_exist_duration_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum by(le, risingwave_component, pod, table_id) (rate(state_store_may_exist_duration_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "avg - {{table_id}} {{risingwave_component}} @ {{pod}}"
    }
   ]
  },
  {
   "title": "Read Bloom Filter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_bloom_filter_true_negative_counts{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (risingwave_component,pod,table_id,type)",
     "legendFormat": "bloom filter true negative  - {{table_id}} - {{type}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "sum(rate(state_store_read_req_positive_but_non_exist_counts{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (risingwave_component,pod,table_id,type)",
     "legendFormat": "bloom filter false positive count  - {{table_id}} - {{type}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "sum(rate(state_store_read_req_bloom_filter_positive_counts{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (risingwave_component,pod,table_id,type)",
     "legendFormat": "read_req bloom filter positive - {{table_id}} - {{type}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "sum(rate(state_store_read_req_check_bloom_filter_counts{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (risingwave_component,pod,table_id,type)",
     "legendFormat": "read_req check bloom filter - {{table_id}} - {{type}} @ {{risingwave_component}} @ {{pod}}"
    }
   ]
  },
  {
   "title": "Iter keys flow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_iter_scan_key_counts{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (pod, type, table_id)",
     "legendFormat": "iter keys flow - {{table_id}} @ {{type}} @ {{pod}} "
    }
   ]
  },
  {
   "title": " Filter/Cache Miss Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (sum(rate(state_store_bloom_filter_true_negative_counts{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (risingwave_component,pod,table_id,type)) / (sum(rate(state_bloom_filter_check_counts{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (risingwave_component,pod,table_id,type))",
     "legendFormat": "bloom filter miss rate - {{table_id}} - {{type}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "(sum(rate(state_store_sst_store_block_request_counts{type='meta_miss',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (risingwave_component,pod,table_id)) / (sum(rate(state_store_sst_store_block_request_counts{type='meta_total',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (risingwave_component,pod,table_id))",
     "legendFormat": "meta cache miss rate - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "(sum(rate(state_store_sst_store_block_request_counts{type='data_miss',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (risingwave_component,pod,table_id)) / (sum(rate(state_store_sst_store_block_request_counts{type='data_total',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (risingwave_component,pod,table_id))",
     "legendFormat": "block cache miss rate - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "(sum(rate(file_cache_miss{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (pod)) / (sum(rate(file_cache_latency_count{op='get',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (pod))",
     "legendFormat": "file cache miss rate @ {{pod}}"
    },
    {
     "expr": "1 - (((sum(rate(state_store_read_req_bloom_filter_positive_counts{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (risingwave_component,pod,table_id,type))) / (sum(rate(state_store_read_req_check_bloom_filter_counts{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (risingwave_component,pod,table_id,type)))",
     "legendFormat": "read req bloom filter filter rate - {{table_id}} - {{type}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "1 - (((sum(rate(state_store_read_req_positive_but_non_exist_counts{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (risingwave_component,pod,table_id,type))) / (sum(rate(state_store_read_req_bloom_filter_positive_counts{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (risingwave_component,pod,table_id,type)))",
     "legendFormat": "read req bloom filter false positive rate - {{table_id}} - {{type}} @ {{risingwave_component}} @ {{pod}}"
    }
   ]
  },
  {
   "title": "Read Merged SSTs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_iter_merge_sstable_counts_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, table_id, type))",
     "legendFormat": "# merged ssts p90 - {{table_id}} @ {{risingwave_component}} @ {{type}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_iter_merge_sstable_counts_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, table_id, type))",
     "legendFormat": "# merged ssts p99 - {{table_id}} @ {{risingwave_component}} @ {{type}}"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(state_store_iter_merge_sstable_counts_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, table_id, type))",
     "legendFormat": "# merged ssts pmax - {{table_id}} @ {{risingwave_component}} @ {{type}}"
    },
    {
     "expr": "sum by(le, risingwave_component, pod, table_id)(rate(state_store_iter_merge_sstable_counts_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))  / sum by(le, risingwave_component, pod, table_id)(rate(state_store_iter_merge_sstable_counts_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "# merged ssts avg  - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    }
   ]
  },
  {
   "title": "Write Ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_write_batch_duration_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (risingwave_component,pod,table_id)",
     "legendFormat": "write batch - {{table_id}} @ {{risingwave_component}} @ {{pod}} "
    },
    {
     "expr": "sum(rate(state_store_sync_duration_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (risingwave_component,pod)",
     "legendFormat": "l0 - {{risingwave_component}} @ {{pod}} "
    }
   ]
  },
  {
   "title": "Write Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(state_store_write_batch_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "write to shared_buffer p50 - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_write_batch_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "write to shared_buffer p90 - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_write_batch_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "write to shared_buffer p99 - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(state_store_write_batch_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "write to shared_buffer pmax - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "sum by(le, risingwave_component, pod, table_id)(rate(state_store_write_batch_duration_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))  / sum by(le, risingwave_component, pod, table_id)(rate(state_store_write_batch_duration_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "write to shared_buffer avg - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(state_store_write_shared_buffer_sync_time_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
     "legendFormat": "write to object_store p50 - {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_write_shared_buffer_sync_time_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
     "legendFormat": "write to object_store p90 - {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_write_shared_buffer_sync_time_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
     "legendFormat": "write to object_store p99 - {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(state_store_write_shared_buffer_sync_time_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
     "legendFormat": "write to object_store pmax - {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "sum by(le, risingwave_component, pod)(rate(state_store_write_shared_buffer_sync_time_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))  / sum by(le, risingwave_component, pod)(rate(state_store_write_shared_buffer_sync_time_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "write to object_store - {{risingwave_component}} @ {{pod}}"
    }
   ]
  },
  {
   "title": "Write Item Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_write_batch_tuple_counts{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (risingwave_component,pod,table_id)",
     "legendFormat": "write_batch_kv_pair_count - {{table_id}} @ {{pod}} "
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_write_batch_size_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))by(risingwave_component,pod) / sum(rate(state_store_write_batch_size_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))by(risingwave_component,pod,table_id)",
     "legendFormat": "shared_buffer - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "sum(rate(compactor_shared_buffer_to_sstable_size{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))by(risingwave_component,pod) / sum(rate(state_store_shared_buffer_to_sstable_size_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))by(risingwave_component,pod)",
     "legendFormat": "sync - {{risingwave_component}} @ {{pod}}"
    }
   ]
  },
  {
   "title": "Checkpoint Sync Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(state_store_sync_size_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
     "legendFormat": "p50 - {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_sync_size_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
     "legendFormat": "p90 - {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_sync_size_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
     "legendFormat": "p99 - {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(state_store_sync_size_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
     "legendFormat": "pmax - {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "sum by(le, risingwave_component, pod) (rate(state_store_sync_size_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum by(le, risingwave_component, pod) (rate(state_store_sync_size_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "avg - {{risingwave_component}} @ {{pod}}"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(state_store_meta_cache_size{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}) by (risingwave_component,pod)",
     "legendFormat": "meta cache - {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "avg(state_store_block_cache_size{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}) by (risingwave_component,pod)",
     "legendFormat": "data cache - {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "sum(state_store_limit_memory_size{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}) by (risingwave_component)",
     "legendFormat": "uploading memory - {{risingwave_component}}"
    }
   ]
  },
  {
   "title": "Row SeqScan Next Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(batch_row_seq_scan_next_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
     "legendFormat": "row_seq_scan next p50 - {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(batch_row_seq_scan_next_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
     "legendFormat": "row_seq_scan next p90 - {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(batch_row_seq_scan_next_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
     "legendFormat": "row_seq_scan next p99 - {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(batch_row_seq_scan_next_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
     "legendFormat": "row_seq_scan next pmax - {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "sum by(le, risingwave_component, pod) (rate(batch_row_seq_scan_next_duration_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum by(le, risingwave_component, pod) (rate(batch_row_seq_scan_next_duration_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "row_seq_scan next avg - {{risingwave_component}} @ {{pod}}"
    }
   ]
  },
  {
   "title": "Fetch Meta Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(state_store_iter_fetch_meta_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "fetch_meta_duration p50 - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_iter_fetch_meta_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "fetch_meta_duration p90 - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_iter_fetch_meta_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "fetch_meta_duration p99 - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(state_store_iter_fetch_meta_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
     "legendFormat": "fetch_meta_duration pmax - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    },
    {
     "expr": "sum by(le, risingwave_component, pod, table_id) (rate(state_store_iter_fetch_meta_duration_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum by(le, risingwave_component, pod, table_id) (rate(state_store_iter_fetch_meta_duration_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "fetch_meta_duration avg - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
    }
   ]
  },
  {
   "title": "Compaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 167 },
   "collapsed": true,
   "panels": [
    {
     "title": "SST Count",
     "type": "timeseries",
     "description": "num of SSTs in each level",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "sum(storage_level_sst_num{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}) by (pod, level_index)",
       "legendFormat": "L{{level_index}}"
      }
     ]
    },
    {
     "title": "KBs level sst",
     "type": "timeseries",
     "description": "KBs total file bytes in each level",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "sum(storage_level_total_file_size{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}) by (pod, level_index)",
       "legendFormat": "L{{level_index}}"
      }
     ]
    },
    {
     "title": "Compaction Success & Failure Count",
     "type": "timeseries",
     "description": "num of compactions from each level to next level",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(storage_level_compact_frequency{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}) by (compactor, group, task_type, result)",
       "legendFormat": "{{task_type}} - {{result}} - group-{{group}} @ {{compactor}}"
      }
     ]
    },
    {
     "title": "Compaction Skip Count",
     "type": "timeseries",
     "description": "num of compaction task which does not trigger",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "sum(rate(storage_skip_compact_frequency{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (level, type)",
       "legendFormat": "{{level}}-{{type}}"
      }
     ]
    },
    {
     "title": "Compactor Running Task Count",
     "type": "timeseries",
     "description": "num of compactions from each level to next level",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "avg(storage_compact_task_pending_num{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}) by(risingwave_component, pod)",
       "legendFormat": "compactor_task_split_count - {{risingwave_component}} @ {{pod}}"
      }
     ]
    },
    {
     "title": "Compaction Duration",
     "type": "timeseries",
     "description": "Total time of compact that have been issued to state store",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(compactor_compact_task_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "compact-task p50 - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(compactor_compact_task_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "compact-task p90 - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(1.0, sum(rate(compactor_compact_task_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "compact-task pmax - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(compactor_compact_sst_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "compact-key-range p90 - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(1.0, sum(rate(compactor_compact_sst_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "compact-key-range pmax - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(compactor_get_table_id_total_time_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "get-table-id p90 - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(1.0, sum(rate(compactor_get_table_id_total_time_duration_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "get-table-id pmax - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(compactor_remote_read_time_per_task_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "remote-io p90 - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(1.0, sum(rate(compactor_remote_read_time_per_task_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "remote-io pmax - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "sum by(le)(rate(compactor_compact_task_duration_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum by(le)(rate(compactor_compact_task_duration_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "compact-task avg"
      },
      {
       "expr": "sum by(le)(rate(state_store_compact_sst_duration_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum by(le)(rate(state_store_compact_sst_duration_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "compact-key-range avg"
      }
     ]
    },
    {
     "title": "Compaction Throughput",
     "type": "timeseries",
     "description": "KBs read from next level during history compactions to next level",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(storage_level_compact_read_next{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by(risingwave_component,pod) + sum(rate(storage_level_compact_read_curr{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by(risingwave_component,pod)",
       "legendFormat": "read - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "sum(rate(storage_level_compact_write{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by(risingwave_component,pod)",
       "legendFormat": "write - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "sum(rate(compactor_write_build_l0_bytes{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))by (risingwave_component,pod)",
       "legendFormat": "flush - {{risingwave_component}} @ {{pod}}"
      }
     ]
    },
    {
     "title": "Compaction Write Bytes",
     "type": "timeseries",
     "description": "num of SSTs written into next level during history compactions to next level",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(storage_level_compact_write{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}) by (risingwave_component)",
       "legendFormat": "write - {{risingwave_component}}"
      },
      {
       "expr": "sum(compactor_write_build_l0_bytes{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}) by (risingwave_component)",
       "legendFormat": "flush - {{risingwave_component}}"
      }
     ]
    },
    {
     "title": "Compaction Write Amplification",
     "type": "timeseries",
     "description": "num of SSTs written into next level during history compactions to next level",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(storage_level_compact_write{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}) / sum(state_store_write_build_l0_bytes{namespace=~\"$namespace\",risingwave_name=~\"$instance\"})",
       "legendFormat": "write amplification"
      }
     ]
    },
    {
     "title": "Compacting SST Count",
     "type": "timeseries",
     "description": "num of SSTs to be merged to next level in each level",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "storage_level_compact_cnt{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}",
       "legendFormat": "L{{level_index}}"
      }
     ]
    },
    {
     "title": "KBs Read from Next Level",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(storage_level_compact_read_next{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, level_index)",
       "legendFormat": "L{{level_index}} read"
      }
     ]
    },
    {
     "title": "KBs Read from Current Level",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(storage_level_compact_read_curr{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, level_index)",
       "legendFormat": "L{{level_index}} read"
      }
     ]
    },
    {
     "title": "Count of SSTs Read from Current Level",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(storage_level_compact_read_sstn_curr{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, level_index)",
       "legendFormat": "L{{level_index}} read"
      }
     ]
    },
    {
     "title": "KBs Written to Next Level",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(storage_level_compact_write{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, level_index)",
       "legendFormat": "L{{level_index}} write"
      }
     ]
    },
    {
     "title": "Count of SSTs Written to Next Level",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(storage_level_compact_write_sstn{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, level_index)",
       "legendFormat": "L{{level_index}} write"
      }
     ]
    },
    {
     "title": "Count of SSTs Read from Next Level",
     "type": "timeseries",
     "description": "num of SSTs read from next level during history compactions to next level",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(storage_level_compact_read_sstn_next{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, level_index)",
       "legendFormat": "L{{level_index}} read"
      }
     ]
    },
    {
     "title": "Hummock Sstable Size",
     "type": "timeseries",
     "description": "Total bytes gotten from sstable_bloom_filter, for observing bloom_filter size",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(le, risingwave_component, pod)(rate(compactor_sstable_bloom_filter_size_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))  / sum by(le, risingwave_component, pod)(rate(compactor_sstable_bloom_filter_size_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "avg_meta - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "sum by(le, risingwave_component, pod)(rate(compactor_sstable_file_size_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))  / sum by(le, risingwave_component, pod)(rate(compactor_sstable_file_size_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "avg_file - {{risingwave_component}} @ {{pod}}"
      }
     ]
    },
    {
     "title": "Hummock Sstable Item Size",
     "type": "timeseries",
     "description": "Total bytes gotten from sstable_avg_key_size, for observing sstable_avg_key_size",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(le, risingwave_component, pod)(rate(compactor_sstable_avg_key_size_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))  / sum by(le, risingwave_component, pod)(rate(state_store_sstable_avg_key_size_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "avg_key_size - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "sum by(le, risingwave_component, pod)(rate(compactor_sstable_avg_value_size_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))  / sum by(le, risingwave_component, pod)(rate(compactor_sstable_avg_value_size_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "avg_value_size - {{risingwave_component}} @ {{pod}}"
      }
     ]
    },
    {
     "title": "Hummock Remote Read Duration",
     "type": "timeseries",
     "description": "Total time of operations which read from remote storage when enable prefetch",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(rate(state_store_remote_read_time_per_task_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
       "legendFormat": "remote-io p90 - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(1.0, sum(rate(state_store_remote_read_time_per_task_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod, table_id))",
       "legendFormat": "remote-io pmax - {{table_id}} @ {{risingwave_component}} @ {{pod}}"
      }
     ]
    },
    {
     "title": "Compactor Iter keys",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(compactor_iter_scan_key_counts{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (pod, type)",
       "legendFormat": "iter keys flow - {{type}} @ {{pod}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Object Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 168 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operation Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(object_store_read_bytes{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))by(risingwave_component,pod)",
       "legendFormat": "read - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "sum(rate(object_store_write_bytes{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))by(risingwave_component,pod)",
       "legendFormat": "write - {{risingwave_component}} @ {{pod}}"
      }
     ]
    },
    {
     "title": "Operation Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(object_store_operation_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, type, risingwave_component, pod))",
       "legendFormat": "{{type}} p50 - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(object_store_operation_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, type, risingwave_component, pod))",
       "legendFormat": "{{type}} p90 - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(object_store_operation_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, type, risingwave_component, pod))",
       "legendFormat": "{{type}} p99 - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(1.0, sum(rate(object_store_operation_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, type, risingwave_component, pod))",
       "legendFormat": "{{type}} pmax - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "sum by(le, type, risingwave_component, pod)(rate(object_store_operation_latency_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum by(le, type, risingwave_component, pod) (rate(object_store_operation_latency_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{type}} avg - {{risingwave_component}} @ {{pod}}"
      }
     ]
    },
    {
     "title": "Operation Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(object_store_operation_latency_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, type, risingwave_component, pod)",
       "legendFormat": "{{type}} - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "sum(rate(object_store_operation_latency_count{type=~'upload|delete',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, media_type, risingwave_component, pod)",
       "legendFormat": "{{media_type}}-write - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "sum(rate(object_store_operation_latency_count{type=~'read|readv|list|metadata',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, media_type, risingwave_component, pod)",
       "legendFormat": "{{media_type}}-read - {{risingwave_component}} @ {{pod}}"
      }
     ]
    },
    {
     "title": "Operation Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(object_store_operation_bytes_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, type, risingwave_component, pod))",
       "legendFormat": "{{type}} p50 - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(object_store_operation_bytes_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, type, risingwave_component, pod))",
       "legendFormat": "{{type}} p90 - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(object_store_operation_bytes_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, type, risingwave_component, pod))",
       "legendFormat": "{{type}} p99 - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(1.0, sum(rate(object_store_operation_bytes_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, type, risingwave_component, pod))",
       "legendFormat": "{{type}} pmax - {{risingwave_component}} @ {{pod}}"
      }
     ]
    },
    {
     "title": "Operation Failure Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(object_store_failure_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (pod, risingwave_component, type)",
       "legendFormat": "{{type}} - {{risingwave_component}} @ {{pod}}"
      }
     ]
    },
    {
     "title": "Estimated S3 Cost (Realtime)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "$" } },
     "targets": [
      {
       "expr": "sum(object_store_operation_latency_count{type=~'read|streaming_read_start|delete',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}) * 0.0004 / 1000",
       "legendFormat": "GET, SELECT, and all other Requests Cost"
      },
      {
       "expr": "sum(object_store_operation_latency_count{type=~'upload|streaming_upload_start|s3_upload_part|streaming_upload_finish|delete_objects|list',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}) * 0.005 / 1000",
       "legendFormat": "PUT, COPY, POST, LIST Requests Cost"
      }
     ]
    },
    {
     "title": "Estimated S3 Cost (Monthly)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "$" } },
     "targets": [
      {
       "expr": "sum(storage_level_total_file_size{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}) by (pod) * 0.023 / 1000 / 1000",
       "legendFormat": "Monthly Storage Cost"
      }
     ]
    }
   ]
  },
  {
   "title": "Hummock Tiered Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 169 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(file_cache_latency_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (op, pod)",
       "legendFormat": "file cache {{op}} @ {{pod}}"
      },
      {
       "expr": "sum(rate(file_cache_miss{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (pod)",
       "legendFormat": "file cache miss @ {{pod}}"
      },
      {
       "expr": "sum(rate(file_cache_disk_latency_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (op, pod)",
       "legendFormat": "file cache disk {{op}} @ {{pod}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(file_cache_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, op, pod))",
       "legendFormat": "p50 - file cache - {{op}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(file_cache_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, op, pod))",
       "legendFormat": "p90 - file cache - {{op}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(file_cache_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, op, pod))",
       "legendFormat": "p99 - file cache - {{op}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(1.0, sum(rate(file_cache_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, op, pod))",
       "legendFormat": "pmax - file cache - {{op}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(file_cache_disk_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, op, pod))",
       "legendFormat": "p50 - file cache disk - {{op}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(file_cache_disk_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, op, pod))",
       "legendFormat": "p90 - file cache disk - {{op}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(file_cache_disk_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, op, pod))",
       "legendFormat": "p99 - file cache disk - {{op}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(1.0, sum(rate(file_cache_disk_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, op, pod))",
       "legendFormat": "pmax - file cache disk - {{op}} @ {{pod}}"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(file_cache_disk_bytes{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (op, pod)",
       "legendFormat": "disk {{op}} @ {{pod}}"
      }
     ]
    },
    {
     "title": "Disk IO Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(file_cache_disk_io_size_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, op, pod))",
       "legendFormat": "p50 - file cache disk - {{op}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(file_cache_disk_io_size_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, op, pod))",
       "legendFormat": "p90 - file cache disk - {{op}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(file_cache_disk_io_size_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, op, pod))",
       "legendFormat": "p99 - file cache disk - {{op}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(1.0, sum(rate(file_cache_disk_io_size_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, op, pod))",
       "legendFormat": "pmax - file cache disk - {{op}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(file_cache_disk_read_entry_size_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, op, pod))",
       "legendFormat": "p50 - file cache disk read entry - {{op}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(file_cache_disk_read_entry_size_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, op, pod))",
       "legendFormat": "p90 - file cache disk read entry - {{op}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(file_cache_disk_read_entry_size_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, op, pod))",
       "legendFormat": "p99 - file cache disk read entry - {{op}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(1.0, sum(rate(file_cache_disk_read_entry_size_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, op, pod))",
       "legendFormat": "pmax - file cache disk read entry - {{op}} @ {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hummock Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 170 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lock Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(hummock_manager_lock_time_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, lock_name, lock_type))",
       "legendFormat": "Lock Time p50 - {{lock_type}} @ {{lock_name}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(hummock_manager_lock_time_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, lock_name, lock_type))",
       "legendFormat": "Lock Time p99 - {{lock_type}} @ {{lock_name}}"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(hummock_manager_lock_time_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, lock_name, lock_type))",
       "legendFormat": "Lock Time p999 - {{lock_type}} @ {{lock_name}}"
      },
      {
       "expr": "histogram_quantile(1.0, sum(rate(hummock_manager_lock_time_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, lock_name, lock_type))",
       "legendFormat": "Lock Time pmax - {{lock_type}} @ {{lock_name}}"
      }
     ]
    },
    {
     "title": "Real Process Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(meta_hummock_manager_real_process_time_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, method))",
       "legendFormat": "Real Process Time p50 - {{method}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(meta_hummock_manager_real_process_time_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, method))",
       "legendFormat": "Real Process Time p99 - {{method}}"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(meta_hummock_manager_real_process_time_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, method))",
       "legendFormat": "Real Process Time p999 - {{method}}"
      },
      {
       "expr": "histogram_quantile(1.0, sum(rate(meta_hummock_manager_real_process_time_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, method))",
       "legendFormat": "Real Process Time pmax - {{method}}"
      }
     ]
    },
    {
     "title": "Version Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "storage_version_size{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}",
       "legendFormat": "version size"
      }
     ]
    },
    {
     "title": "Version Id",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "storage_current_version_id{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}",
       "legendFormat": "current version id"
      },
      {
       "expr": "storage_checkpoint_version_id{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}",
       "legendFormat": "checkpoint version id"
      },
      {
       "expr": "storage_min_pinned_version_id{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}",
       "legendFormat": "min pinned version id"
      },
      {
       "expr": "storage_min_safepoint_version_id{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}",
       "legendFormat": "min safepoint version id"
      }
     ]
    },
    {
     "title": "Epoch",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "storage_max_committed_epoch{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}",
       "legendFormat": "max committed epoch"
      },
      {
       "expr": "storage_safe_epoch{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}",
       "legendFormat": "safe epoch"
      },
      {
       "expr": "storage_min_pinned_epoch{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}",
       "legendFormat": "min pinned epoch"
      }
     ]
    },
    {
     "title": "Table KV Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "storage_version_stats{metric='total_key_size',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}/1024",
       "legendFormat": "table{{table_id}} {{metric}}"
      },
      {
       "expr": "storage_version_stats{metric='total_value_size',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}/1024",
       "legendFormat": "table{{table_id}} {{metric}}"
      }
     ]
    },
    {
     "title": "Table KV Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "storage_version_stats{metric='total_key_count',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}",
       "legendFormat": "table{{table_id}} {{metric}}"
      }
     ]
    },
    {
     "title": "Stale SST Total Number",
     "type": "timeseries",
     "description": "total number of SSTs that is no longer referenced by versions but is not yet deleted from storage",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "storage_stale_ssts_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}",
       "legendFormat": "stale SST total number"
      }
     ]
    }
   ]
  },
  {
   "title": "Backup Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 171 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "backup_job_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}",
       "legendFormat": "job count"
      }
     ]
    },
    {
     "title": "Job Process Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(backup_job_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, state))",
       "legendFormat": "Job Process Time p50 - {{state}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(backup_job_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, state))",
       "legendFormat": "Job Process Time p99 - {{state}}"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(backup_job_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, state))",
       "legendFormat": "Job Process Time p999 - {{state}}"
      },
      {
       "expr": "histogram_quantile(1.0, sum(rate(backup_job_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, state))",
       "legendFormat": "Job Process Time pmax - {{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC Meta: Catalog Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 172 },
   "collapsed": true,
   "panels": [
    {
     "title": "Create latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.CatalogService/Create',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "Create_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.CatalogService/Create',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "Create_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.CatalogService/Create',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "Create_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path='/meta.CatalogService/Create',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum(irate(meta_grpc_duration_seconds_count{path='/meta.CatalogService/Create',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Create_avg"
      }
     ]
    },
    {
     "title": "Drop latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.CatalogService/Drop',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "Drop_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.CatalogService/Drop',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "Drop_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.CatalogService/Drop',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "Drop_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path='/meta.CatalogService/Drop',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum(irate(meta_grpc_duration_seconds_count{path='/meta.CatalogService/Drop',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Drop_avg"
      }
     ]
    },
    {
     "title": "GetCatalog latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.CatalogService/GetCatalog',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "GetCatalog_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.CatalogService/GetCatalog',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "GetCatalog_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.CatalogService/GetCatalog',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "GetCatalog_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path='/meta.CatalogService/GetCatalog',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum(irate(meta_grpc_duration_seconds_count{path='/meta.CatalogService/GetCatalog',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "GetCatalog_avg"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC Meta: Cluster Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 173 },
   "collapsed": true,
   "panels": [
    {
     "title": "AddWorkerNode latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.ClusterService/AddWorkerNode',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "AddWorkerNode_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.ClusterService/AddWorkerNode',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "AddWorkerNode_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.ClusterService/AddWorkerNode',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "AddWorkerNode_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path='/meta.ClusterService/AddWorkerNode',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum(irate(meta_grpc_duration_seconds_count{path='/meta.ClusterService/AddWorkerNode',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "AddWorkerNode_avg"
      }
     ]
    },
    {
     "title": "ListAllNodes latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.ClusterService/ListAllNodes',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "ListAllNodes_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.ClusterService/ListAllNodes',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "ListAllNodes_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.ClusterService/ListAllNodes',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "ListAllNodes_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path='/meta.ClusterService/ListAllNodes',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum(irate(meta_grpc_duration_seconds_count{path='/meta.ClusterService/ListAllNodes',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "ListAllNodes_avg"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC Meta: Stream Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 174 },
   "collapsed": true,
   "panels": [
    {
     "title": "CreateMaterializedView latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.StreamManagerService/CreateMaterializedView',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "CreateMaterializedView_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.StreamManagerService/CreateMaterializedView',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "CreateMaterializedView_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.StreamManagerService/CreateMaterializedView',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "CreateMaterializedView_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path='/meta.StreamManagerService/CreateMaterializedView',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum(irate(meta_grpc_duration_seconds_count{path='/meta.StreamManagerService/CreateMaterializedView',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "CreateMaterializedView_avg"
      }
     ]
    },
    {
     "title": "DropMaterializedView latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.StreamManagerService/DropMaterializedView',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "DropMaterializedView_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.StreamManagerService/DropMaterializedView',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "DropMaterializedView_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.StreamManagerService/DropMaterializedView',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "DropMaterializedView_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path='/meta.StreamManagerService/DropMaterializedView',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum(irate(meta_grpc_duration_seconds_count{path='/meta.StreamManagerService/DropMaterializedView',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "DropMaterializedView_avg"
      }
     ]
    },
    {
     "title": "Flush latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.StreamManagerService/Flush',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "Flush_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.StreamManagerService/Flush',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "Flush_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.StreamManagerService/Flush',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "Flush_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path='/meta.StreamManagerService/Flush',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum(irate(meta_grpc_duration_seconds_count{path='/meta.StreamManagerService/Flush',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Flush_avg"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC Meta: Hummock Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 175 },
   "collapsed": true,
   "panels": [
    {
     "title": "UnpinVersionBefore latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.HummockManagerService/UnpinVersionBefore',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "UnpinVersionBefore_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.HummockManagerService/UnpinVersionBefore',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "UnpinVersionBefore_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.HummockManagerService/UnpinVersionBefore',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "UnpinVersionBefore_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path='/meta.HummockManagerService/UnpinVersionBefore',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum(irate(meta_grpc_duration_seconds_count{path='/meta.HummockManagerService/UnpinVersionBefore',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "UnpinVersionBefore_avg"
      }
     ]
    },
    {
     "title": "UnpinSnapshotBefore latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.HummockManagerService/UnpinSnapshotBefore',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "UnpinSnapshotBefore_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.HummockManagerService/UnpinSnapshotBefore',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "UnpinSnapshotBefore_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.HummockManagerService/UnpinSnapshotBefore',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "UnpinSnapshotBefore_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path='/meta.HummockManagerService/UnpinSnapshotBefore',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum(irate(meta_grpc_duration_seconds_count{path='/meta.HummockManagerService/UnpinSnapshotBefore',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "UnpinSnapshotBefore_avg"
      }
     ]
    },
    {
     "title": "ReportCompactionTasks latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.HummockManagerService/ReportCompactionTasks',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "ReportCompactionTasks_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.HummockManagerService/ReportCompactionTasks',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "ReportCompactionTasks_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.HummockManagerService/ReportCompactionTasks',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "ReportCompactionTasks_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path='/meta.HummockManagerService/ReportCompactionTasks',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum(irate(meta_grpc_duration_seconds_count{path='/meta.HummockManagerService/ReportCompactionTasks',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "ReportCompactionTasks_avg"
      }
     ]
    },
    {
     "title": "GetNewSstIds latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.HummockManagerService/GetNewSstIds',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "GetNewSstIds_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.HummockManagerService/GetNewSstIds',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "GetNewSstIds_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path='/meta.HummockManagerService/GetNewSstIds',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "GetNewSstIds_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path='/meta.HummockManagerService/GetNewSstIds',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum(irate(meta_grpc_duration_seconds_count{path='/meta.HummockManagerService/GetNewSstIds',namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "GetNewSstIds_avg"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC: Hummock Meta Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 176 },
   "collapsed": true,
   "panels": [
    {
     "title": "compaction_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "sum(irate(state_store_report_compaction_task_counts{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by(risingwave_component,pod)",
       "legendFormat": "report_compaction_task_counts - {{pod}} "
      }
     ]
    },
    {
     "title": "version_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_unpin_version_before_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "unpin_version_before_latency_p50 - {{pod}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_unpin_version_before_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "unpin_version_before_latency_p99 - {{pod}} "
      },
      {
       "expr": "sum(irate(state_store_unpin_version_before_latency_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum(irate(state_store_unpin_version_before_latency_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "unpin_version_before_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(state_store_unpin_version_before_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "unpin_version_before_latency_p90 - {{pod}} "
      }
     ]
    },
    {
     "title": "snapshot_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_pin_snapshot_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "pin_snapshot_latency_p50 - {{pod}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_pin_snapshot_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "pin_snapshot_latency_p99 - {{pod}} "
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(state_store_pin_snapshot_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "pin_snapshot_latencyp90 - {{pod}} "
      },
      {
       "expr": "sum(irate(state_store_pin_snapshot_latency_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum(irate(state_store_pin_snapshot_latency_count[$__rate_interval]))",
       "legendFormat": "pin_snapshot_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_unpin_version_snapshot_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "unpin_snapshot_latency_p50 - {{pod}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_unpin_version_snapshot_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "unpin_snapshot_latency_p99 - {{pod}} "
      },
      {
       "expr": "sum(irate(state_store_unpin_snapshot_latency_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum(irate(state_store_unpin_snapshot_latency_count[$__rate_interval]))",
       "legendFormat": "unpin_snapshot_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(state_store_unpin_snapshot_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "unpin_snapshot_latency_p90 - {{pod}} "
      }
     ]
    },
    {
     "title": "snapshot_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "sum(irate(state_store_pin_snapshot_counts{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by(risingwave_component,pod)",
       "legendFormat": "pin_snapshot_counts - {{pod}} "
      },
      {
       "expr": "sum(irate(state_store_unpin_snapshot_counts{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by(risingwave_component,pod)",
       "legendFormat": "unpin_snapshot_counts - {{pod}} "
      }
     ]
    },
    {
     "title": "table_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_get_new_sst_ids_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "get_new_sst_ids_latency_latency_p50 - {{pod}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_get_new_sst_ids_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "get_new_sst_ids_latency_latency_p99 - {{pod}} "
      },
      {
       "expr": "sum(irate(state_store_get_new_sst_ids_latency_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum(irate(state_store_get_new_sst_ids_latency_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "get_new_sst_ids_latency_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(state_store_get_new_sst_ids_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "get_new_sst_ids_latency_latency_p90 - {{pod}} "
      }
     ]
    },
    {
     "title": "table_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "sum(irate(state_store_get_new_sst_ids_latency_counts{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval]))by(risingwave_component,pod)",
       "legendFormat": "get_new_sst_ids_latency_counts - {{pod}} "
      }
     ]
    },
    {
     "title": "compaction_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_report_compaction_task_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "report_compaction_task_latency_p50 - {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_report_compaction_task_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "report_compaction_task_latency_p99 - {{pod}}"
      },
      {
       "expr": "sum(irate(state_store_report_compaction_task_latency_sum{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) / sum(irate(state_store_report_compaction_task_latency_count[$__rate_interval]))",
       "legendFormat": "report_compaction_task_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(state_store_report_compaction_task_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "report_compaction_task_latency_p90 - {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Frontend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 177 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Per second in Loacl Execution Mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "Qps" } },
     "targets": [
      {
       "expr": "rate(frontend_query_counter_local_execution{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Query Per second in Distributed Execution Mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "Qps" } },
     "targets": [
      {
       "expr": "rate(distributed_completed_query_counter{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Running query in distributed execution mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "distributed_running_query_num{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}",
       "legendFormat": "The number of running query in distributed execution mode"
      }
     ]
    },
    {
     "title": "Rejected query in distributed execution mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "distributed_rejected_query_counter{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}",
       "legendFormat": "The number of rejected query in distributed execution mode"
      }
     ]
    },
    {
     "title": "Completed query in distributed execution mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "distributed_completed_query_counter{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}",
       "legendFormat": "The number of completed query in distributed execution mode"
      }
     ]
    },
    {
     "title": "Query Latency in Distributed Execution Mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(distributed_query_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "p50 - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(distributed_query_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "p90 - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(distributed_query_latency_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "p99 - {{risingwave_component}} @ {{pod}}"
      }
     ]
    },
    {
     "title": "Query Latency in Local Execution Mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(frontend_latency_local_execution_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "p50 - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(frontend_latency_local_execution_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "p90 - {{risingwave_component}} @ {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(frontend_latency_local_execution_bucket{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])) by (le, risingwave_component, pod))",
       "legendFormat": "p99 - {{risingwave_component}} @ {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 178 },
   "collapsed": true,
   "panels": [
    {
     "title": "LRU manager loop count per sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "rate(lru_runtime_loop_count{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "LRU manager watermark steps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "targets": [
      {
       "expr": "lru_watermark_step{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "LRU manager diff between watermark_time and now (ms)",
     "type": "timeseries",
     "description": "watermark_time is the current lower watermark of cached data. physical_now is the current time of the machine. The diff (physical_now - watermark_time) shows how much data is cached.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "lru_physical_now_ms{namespace=~\"$namespace\",risingwave_name=~\"$instance\"} - lru_current_watermark_time_ms{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "The memory allocated by jemalloc",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jemalloc_allocated_bytes{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "The memory allocated by streaming",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "stream_total_mem_usage{namespace=~\"$namespace\",risingwave_name=~\"$instance\"}"
      }
     ]
    }
   ]
  }
 ]
}