//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 * Copyright 2023 RisingWave Labs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"github.com/openkruise/kruise-api/apps/pub"
	appsv1 "k8s.io/api/apps/v1"
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PartialObjectMeta) DeepCopyInto(out *PartialObjectMeta) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PartialObjectMeta.
func (in *PartialObjectMeta) DeepCopy() *PartialObjectMeta {
	if in == nil {
		return nil
	}
	out := new(PartialObjectMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentVolumeClaim) DeepCopyInto(out *PersistentVolumeClaim) {
	*out = *in
	in.PersistentVolumeClaimPartialObjectMeta.DeepCopyInto(&out.PersistentVolumeClaimPartialObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentVolumeClaim.
func (in *PersistentVolumeClaim) DeepCopy() *PersistentVolumeClaim {
	if in == nil {
		return nil
	}
	out := new(PersistentVolumeClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentVolumeClaimPartialObjectMeta) DeepCopyInto(out *PersistentVolumeClaimPartialObjectMeta) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Finalizers != nil {
		in, out := &in.Finalizers, &out.Finalizers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentVolumeClaimPartialObjectMeta.
func (in *PersistentVolumeClaimPartialObjectMeta) DeepCopy() *PersistentVolumeClaimPartialObjectMeta {
	if in == nil {
		return nil
	}
	out := new(PersistentVolumeClaimPartialObjectMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWave) DeepCopyInto(out *RisingWave) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWave.
func (in *RisingWave) DeepCopy() *RisingWave {
	if in == nil {
		return nil
	}
	out := new(RisingWave)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RisingWave) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveComponent) DeepCopyInto(out *RisingWaveComponent) {
	*out = *in
	if in.DisallowPrintStackTraces != nil {
		in, out := &in.DisallowPrintStackTraces, &out.DisallowPrintStackTraces
		*out = new(bool)
		**out = **in
	}
	if in.NodeGroups != nil {
		in, out := &in.NodeGroups, &out.NodeGroups
		*out = make([]RisingWaveNodeGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveComponent.
func (in *RisingWaveComponent) DeepCopy() *RisingWaveComponent {
	if in == nil {
		return nil
	}
	out := new(RisingWaveComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveComponentStatus) DeepCopyInto(out *RisingWaveComponentStatus) {
	*out = *in
	out.Total = in.Total
	if in.NodeGroups != nil {
		in, out := &in.NodeGroups, &out.NodeGroups
		*out = make([]RisingWaveNodeGroupStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveComponentStatus.
func (in *RisingWaveComponentStatus) DeepCopy() *RisingWaveComponentStatus {
	if in == nil {
		return nil
	}
	out := new(RisingWaveComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveCondition) DeepCopyInto(out *RisingWaveCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveCondition.
func (in *RisingWaveCondition) DeepCopy() *RisingWaveCondition {
	if in == nil {
		return nil
	}
	out := new(RisingWaveCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveEtcdCredentials) DeepCopyInto(out *RisingWaveEtcdCredentials) {
	*out = *in
	if in.UsernameKeyRef != nil {
		in, out := &in.UsernameKeyRef, &out.UsernameKeyRef
		*out = new(string)
		**out = **in
	}
	if in.PasswordKeyRef != nil {
		in, out := &in.PasswordKeyRef, &out.PasswordKeyRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveEtcdCredentials.
func (in *RisingWaveEtcdCredentials) DeepCopy() *RisingWaveEtcdCredentials {
	if in == nil {
		return nil
	}
	out := new(RisingWaveEtcdCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveGCSCredentials) DeepCopyInto(out *RisingWaveGCSCredentials) {
	*out = *in
	if in.ServiceAccountCredentialsKeyRef != nil {
		in, out := &in.ServiceAccountCredentialsKeyRef, &out.ServiceAccountCredentialsKeyRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveGCSCredentials.
func (in *RisingWaveGCSCredentials) DeepCopy() *RisingWaveGCSCredentials {
	if in == nil {
		return nil
	}
	out := new(RisingWaveGCSCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveList) DeepCopyInto(out *RisingWaveList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RisingWave, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveList.
func (in *RisingWaveList) DeepCopy() *RisingWaveList {
	if in == nil {
		return nil
	}
	out := new(RisingWaveList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RisingWaveList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveMetaStoreBackend) DeepCopyInto(out *RisingWaveMetaStoreBackend) {
	*out = *in
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(bool)
		**out = **in
	}
	if in.Etcd != nil {
		in, out := &in.Etcd, &out.Etcd
		*out = new(RisingWaveMetaStoreBackendEtcd)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveMetaStoreBackend.
func (in *RisingWaveMetaStoreBackend) DeepCopy() *RisingWaveMetaStoreBackend {
	if in == nil {
		return nil
	}
	out := new(RisingWaveMetaStoreBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveMetaStoreBackendEtcd) DeepCopyInto(out *RisingWaveMetaStoreBackendEtcd) {
	*out = *in
	if in.RisingWaveEtcdCredentials != nil {
		in, out := &in.RisingWaveEtcdCredentials, &out.RisingWaveEtcdCredentials
		*out = new(RisingWaveEtcdCredentials)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveMetaStoreBackendEtcd.
func (in *RisingWaveMetaStoreBackendEtcd) DeepCopy() *RisingWaveMetaStoreBackendEtcd {
	if in == nil {
		return nil
	}
	out := new(RisingWaveMetaStoreBackendEtcd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveMetaStoreStatus) DeepCopyInto(out *RisingWaveMetaStoreStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveMetaStoreStatus.
func (in *RisingWaveMetaStoreStatus) DeepCopy() *RisingWaveMetaStoreStatus {
	if in == nil {
		return nil
	}
	out := new(RisingWaveMetaStoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveMinIOCredentials) DeepCopyInto(out *RisingWaveMinIOCredentials) {
	*out = *in
	if in.UsernameKeyRef != nil {
		in, out := &in.UsernameKeyRef, &out.UsernameKeyRef
		*out = new(string)
		**out = **in
	}
	if in.PasswordKeyRef != nil {
		in, out := &in.PasswordKeyRef, &out.PasswordKeyRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveMinIOCredentials.
func (in *RisingWaveMinIOCredentials) DeepCopy() *RisingWaveMinIOCredentials {
	if in == nil {
		return nil
	}
	out := new(RisingWaveMinIOCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveNodeConfiguration) DeepCopyInto(out *RisingWaveNodeConfiguration) {
	*out = *in
	if in.ConfigMap != nil {
		in, out := &in.ConfigMap, &out.ConfigMap
		*out = new(RisingWaveNodeConfigurationConfigMapSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(RisingWaveNodeConfigurationSecretSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveNodeConfiguration.
func (in *RisingWaveNodeConfiguration) DeepCopy() *RisingWaveNodeConfiguration {
	if in == nil {
		return nil
	}
	out := new(RisingWaveNodeConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveNodeConfigurationConfigMapSource) DeepCopyInto(out *RisingWaveNodeConfigurationConfigMapSource) {
	*out = *in
	if in.Optional != nil {
		in, out := &in.Optional, &out.Optional
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveNodeConfigurationConfigMapSource.
func (in *RisingWaveNodeConfigurationConfigMapSource) DeepCopy() *RisingWaveNodeConfigurationConfigMapSource {
	if in == nil {
		return nil
	}
	out := new(RisingWaveNodeConfigurationConfigMapSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveNodeConfigurationSecretSource) DeepCopyInto(out *RisingWaveNodeConfigurationSecretSource) {
	*out = *in
	if in.Optional != nil {
		in, out := &in.Optional, &out.Optional
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveNodeConfigurationSecretSource.
func (in *RisingWaveNodeConfigurationSecretSource) DeepCopy() *RisingWaveNodeConfigurationSecretSource {
	if in == nil {
		return nil
	}
	out := new(RisingWaveNodeConfigurationSecretSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveNodeContainer) DeepCopyInto(out *RisingWaveNodeContainer) {
	*out = *in
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]v1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]v1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeDevices != nil {
		in, out := &in.VolumeDevices, &out.VolumeDevices
		*out = make([]v1.VolumeDevice, len(*in))
		copy(*out, *in)
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(v1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveNodeContainer.
func (in *RisingWaveNodeContainer) DeepCopy() *RisingWaveNodeContainer {
	if in == nil {
		return nil
	}
	out := new(RisingWaveNodeContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveNodeGroup) DeepCopyInto(out *RisingWaveNodeGroup) {
	*out = *in
	if in.RestartAt != nil {
		in, out := &in.RestartAt, &out.RestartAt
		*out = (*in).DeepCopy()
	}
	if in.Configuration != nil {
		in, out := &in.Configuration, &out.Configuration
		*out = new(RisingWaveNodeConfiguration)
		(*in).DeepCopyInto(*out)
	}
	in.UpgradeStrategy.DeepCopyInto(&out.UpgradeStrategy)
	if in.VolumeClaimTemplates != nil {
		in, out := &in.VolumeClaimTemplates, &out.VolumeClaimTemplates
		*out = make([]PersistentVolumeClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PersistentVolumeClaimRetentionPolicy != nil {
		in, out := &in.PersistentVolumeClaimRetentionPolicy, &out.PersistentVolumeClaimRetentionPolicy
		*out = new(appsv1.StatefulSetPersistentVolumeClaimRetentionPolicy)
		**out = **in
	}
	if in.ProgressDeadlineSeconds != nil {
		in, out := &in.ProgressDeadlineSeconds, &out.ProgressDeadlineSeconds
		*out = new(int32)
		**out = **in
	}
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveNodeGroup.
func (in *RisingWaveNodeGroup) DeepCopy() *RisingWaveNodeGroup {
	if in == nil {
		return nil
	}
	out := new(RisingWaveNodeGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveNodeGroupRollingUpdate) DeepCopyInto(out *RisingWaveNodeGroupRollingUpdate) {
	*out = *in
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.Partition != nil {
		in, out := &in.Partition, &out.Partition
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MaxSurge != nil {
		in, out := &in.MaxSurge, &out.MaxSurge
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveNodeGroupRollingUpdate.
func (in *RisingWaveNodeGroupRollingUpdate) DeepCopy() *RisingWaveNodeGroupRollingUpdate {
	if in == nil {
		return nil
	}
	out := new(RisingWaveNodeGroupRollingUpdate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveNodeGroupStatus) DeepCopyInto(out *RisingWaveNodeGroupStatus) {
	*out = *in
	out.WorkloadReplicaStatus = in.WorkloadReplicaStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveNodeGroupStatus.
func (in *RisingWaveNodeGroupStatus) DeepCopy() *RisingWaveNodeGroupStatus {
	if in == nil {
		return nil
	}
	out := new(RisingWaveNodeGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveNodeGroupUpgradeStrategy) DeepCopyInto(out *RisingWaveNodeGroupUpgradeStrategy) {
	*out = *in
	if in.RollingUpdate != nil {
		in, out := &in.RollingUpdate, &out.RollingUpdate
		*out = new(RisingWaveNodeGroupRollingUpdate)
		(*in).DeepCopyInto(*out)
	}
	if in.InPlaceUpdateStrategy != nil {
		in, out := &in.InPlaceUpdateStrategy, &out.InPlaceUpdateStrategy
		*out = new(pub.InPlaceUpdateStrategy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveNodeGroupUpgradeStrategy.
func (in *RisingWaveNodeGroupUpgradeStrategy) DeepCopy() *RisingWaveNodeGroupUpgradeStrategy {
	if in == nil {
		return nil
	}
	out := new(RisingWaveNodeGroupUpgradeStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveNodePodTemplate) DeepCopyInto(out *RisingWaveNodePodTemplate) {
	*out = *in
	in.PartialObjectMeta.DeepCopyInto(&out.PartialObjectMeta)
	in.RisingWaveNodePodTemplateSpec.DeepCopyInto(&out.RisingWaveNodePodTemplateSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveNodePodTemplate.
func (in *RisingWaveNodePodTemplate) DeepCopy() *RisingWaveNodePodTemplate {
	if in == nil {
		return nil
	}
	out := new(RisingWaveNodePodTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveNodePodTemplateSpec) DeepCopyInto(out *RisingWaveNodePodTemplateSpec) {
	*out = *in
	in.RisingWaveNodeContainer.DeepCopyInto(&out.RisingWaveNodeContainer)
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]v1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ActiveDeadlineSeconds != nil {
		in, out := &in.ActiveDeadlineSeconds, &out.ActiveDeadlineSeconds
		*out = new(int64)
		**out = **in
	}
	if in.TerminationGracePeriodSeconds != nil {
		in, out := &in.TerminationGracePeriodSeconds, &out.TerminationGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AutomountServiceAccountToken != nil {
		in, out := &in.AutomountServiceAccountToken, &out.AutomountServiceAccountToken
		*out = new(bool)
		**out = **in
	}
	if in.ShareProcessNamespace != nil {
		in, out := &in.ShareProcessNamespace, &out.ShareProcessNamespace
		*out = new(bool)
		**out = **in
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(v1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HostAliases != nil {
		in, out := &in.HostAliases, &out.HostAliases
		*out = make([]v1.HostAlias, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int32)
		**out = **in
	}
	if in.DNSConfig != nil {
		in, out := &in.DNSConfig, &out.DNSConfig
		*out = new(v1.PodDNSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RuntimeClassName != nil {
		in, out := &in.RuntimeClassName, &out.RuntimeClassName
		*out = new(string)
		**out = **in
	}
	if in.PreemptionPolicy != nil {
		in, out := &in.PreemptionPolicy, &out.PreemptionPolicy
		*out = new(v1.PreemptionPolicy)
		**out = **in
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]v1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SetHostnameAsFQDN != nil {
		in, out := &in.SetHostnameAsFQDN, &out.SetHostnameAsFQDN
		*out = new(bool)
		**out = **in
	}
	if in.OS != nil {
		in, out := &in.OS, &out.OS
		*out = new(v1.PodOS)
		**out = **in
	}
	if in.HostUsers != nil {
		in, out := &in.HostUsers, &out.HostUsers
		*out = new(bool)
		**out = **in
	}
	if in.AdditionalContainers != nil {
		in, out := &in.AdditionalContainers, &out.AdditionalContainers
		*out = make([]v1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveNodePodTemplateSpec.
func (in *RisingWaveNodePodTemplateSpec) DeepCopy() *RisingWaveNodePodTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(RisingWaveNodePodTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveS3Credentials) DeepCopyInto(out *RisingWaveS3Credentials) {
	*out = *in
	if in.AccessKeyRef != nil {
		in, out := &in.AccessKeyRef, &out.AccessKeyRef
		*out = new(string)
		**out = **in
	}
	if in.SecretAccessKeyRef != nil {
		in, out := &in.SecretAccessKeyRef, &out.SecretAccessKeyRef
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveS3Credentials.
func (in *RisingWaveS3Credentials) DeepCopy() *RisingWaveS3Credentials {
	if in == nil {
		return nil
	}
	out := new(RisingWaveS3Credentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveScaleViewLock) DeepCopyInto(out *RisingWaveScaleViewLock) {
	*out = *in
	out.Reference = in.Reference
	if in.Locks != nil {
		in, out := &in.Locks, &out.Locks
		*out = make([]RisingWaveScaleViewNodeGroupLock, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveScaleViewLock.
func (in *RisingWaveScaleViewLock) DeepCopy() *RisingWaveScaleViewLock {
	if in == nil {
		return nil
	}
	out := new(RisingWaveScaleViewLock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveScaleViewNodeGroupLock) DeepCopyInto(out *RisingWaveScaleViewNodeGroupLock) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveScaleViewNodeGroupLock.
func (in *RisingWaveScaleViewNodeGroupLock) DeepCopy() *RisingWaveScaleViewNodeGroupLock {
	if in == nil {
		return nil
	}
	out := new(RisingWaveScaleViewNodeGroupLock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveScaleViewReference) DeepCopyInto(out *RisingWaveScaleViewReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveScaleViewReference.
func (in *RisingWaveScaleViewReference) DeepCopy() *RisingWaveScaleViewReference {
	if in == nil {
		return nil
	}
	out := new(RisingWaveScaleViewReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveSpec) DeepCopyInto(out *RisingWaveSpec) {
	*out = *in
	if in.UseKruiseWorkloads != nil {
		in, out := &in.UseKruiseWorkloads, &out.UseKruiseWorkloads
		*out = new(bool)
		**out = **in
	}
	if in.SyncPrometheusServiceMonitor != nil {
		in, out := &in.SyncPrometheusServiceMonitor, &out.SyncPrometheusServiceMonitor
		*out = new(bool)
		**out = **in
	}
	in.AdditionalFrontendServiceMetadata.DeepCopyInto(&out.AdditionalFrontendServiceMetadata)
	in.MetaStore.DeepCopyInto(&out.MetaStore)
	in.StateStore.DeepCopyInto(&out.StateStore)
	in.PodTemplate.DeepCopyInto(&out.PodTemplate)
	in.Configuration.DeepCopyInto(&out.Configuration)
	in.MetaComponent.DeepCopyInto(&out.MetaComponent)
	in.FrontendComponent.DeepCopyInto(&out.FrontendComponent)
	in.ComputeComponent.DeepCopyInto(&out.ComputeComponent)
	in.CompactorComponent.DeepCopyInto(&out.CompactorComponent)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveSpec.
func (in *RisingWaveSpec) DeepCopy() *RisingWaveSpec {
	if in == nil {
		return nil
	}
	out := new(RisingWaveSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveStateStoreBackend) DeepCopyInto(out *RisingWaveStateStoreBackend) {
	*out = *in
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(bool)
		**out = **in
	}
	if in.MinIO != nil {
		in, out := &in.MinIO, &out.MinIO
		*out = new(RisingWaveStateStoreBackendMinIO)
		(*in).DeepCopyInto(*out)
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(RisingWaveStateStoreBackendS3)
		(*in).DeepCopyInto(*out)
	}
	if in.S3C != nil {
		in, out := &in.S3C, &out.S3C
		*out = new(RisingWaveStateStoreBackendS3C)
		(*in).DeepCopyInto(*out)
	}
	if in.HDFS != nil {
		in, out := &in.HDFS, &out.HDFS
		*out = new(RisingWaveStateStoreBackendHDFS)
		**out = **in
	}
	if in.GCS != nil {
		in, out := &in.GCS, &out.GCS
		*out = new(RisingWaveStateStoreBackendGCS)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveStateStoreBackend.
func (in *RisingWaveStateStoreBackend) DeepCopy() *RisingWaveStateStoreBackend {
	if in == nil {
		return nil
	}
	out := new(RisingWaveStateStoreBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveStateStoreBackendGCS) DeepCopyInto(out *RisingWaveStateStoreBackendGCS) {
	*out = *in
	in.RisingWaveGCSCredentials.DeepCopyInto(&out.RisingWaveGCSCredentials)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveStateStoreBackendGCS.
func (in *RisingWaveStateStoreBackendGCS) DeepCopy() *RisingWaveStateStoreBackendGCS {
	if in == nil {
		return nil
	}
	out := new(RisingWaveStateStoreBackendGCS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveStateStoreBackendHDFS) DeepCopyInto(out *RisingWaveStateStoreBackendHDFS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveStateStoreBackendHDFS.
func (in *RisingWaveStateStoreBackendHDFS) DeepCopy() *RisingWaveStateStoreBackendHDFS {
	if in == nil {
		return nil
	}
	out := new(RisingWaveStateStoreBackendHDFS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveStateStoreBackendMinIO) DeepCopyInto(out *RisingWaveStateStoreBackendMinIO) {
	*out = *in
	in.RisingWaveMinIOCredentials.DeepCopyInto(&out.RisingWaveMinIOCredentials)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveStateStoreBackendMinIO.
func (in *RisingWaveStateStoreBackendMinIO) DeepCopy() *RisingWaveStateStoreBackendMinIO {
	if in == nil {
		return nil
	}
	out := new(RisingWaveStateStoreBackendMinIO)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveStateStoreBackendS3) DeepCopyInto(out *RisingWaveStateStoreBackendS3) {
	*out = *in
	in.RisingWaveS3Credentials.DeepCopyInto(&out.RisingWaveS3Credentials)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveStateStoreBackendS3.
func (in *RisingWaveStateStoreBackendS3) DeepCopy() *RisingWaveStateStoreBackendS3 {
	if in == nil {
		return nil
	}
	out := new(RisingWaveStateStoreBackendS3)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveStateStoreBackendS3C) DeepCopyInto(out *RisingWaveStateStoreBackendS3C) {
	*out = *in
	in.RisingWaveS3Credentials.DeepCopyInto(&out.RisingWaveS3Credentials)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveStateStoreBackendS3C.
func (in *RisingWaveStateStoreBackendS3C) DeepCopy() *RisingWaveStateStoreBackendS3C {
	if in == nil {
		return nil
	}
	out := new(RisingWaveStateStoreBackendS3C)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveStateStoreStatus) DeepCopyInto(out *RisingWaveStateStoreStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveStateStoreStatus.
func (in *RisingWaveStateStoreStatus) DeepCopy() *RisingWaveStateStoreStatus {
	if in == nil {
		return nil
	}
	out := new(RisingWaveStateStoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RisingWaveStatus) DeepCopyInto(out *RisingWaveStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]RisingWaveCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.MetaStore = in.MetaStore
	out.StateStore = in.StateStore
	in.MetaComponent.DeepCopyInto(&out.MetaComponent)
	in.FrontendComponent.DeepCopyInto(&out.FrontendComponent)
	in.ComputeComponent.DeepCopyInto(&out.ComputeComponent)
	in.CompactorComponent.DeepCopyInto(&out.CompactorComponent)
	if in.ScaleViewLocks != nil {
		in, out := &in.ScaleViewLocks, &out.ScaleViewLocks
		*out = make([]RisingWaveScaleViewLock, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RisingWaveStatus.
func (in *RisingWaveStatus) DeepCopy() *RisingWaveStatus {
	if in == nil {
		return nil
	}
	out := new(RisingWaveStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadReplicaStatus) DeepCopyInto(out *WorkloadReplicaStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadReplicaStatus.
func (in *WorkloadReplicaStatus) DeepCopy() *WorkloadReplicaStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadReplicaStatus)
	in.DeepCopyInto(out)
	return out
}
